### PR TITLE
chore: These siunitx options were replaced.

### PR DESCRIPTION
**Pull request by holgerdell**
The siunitx package was somewhat recently updated.

### CODE REVIEW

**Comment by Pseudomanifold** [comment]
Great, thanks! Will do some cosmetic updates afterwards.

**Comment by Pseudomanifold** [comment]
Hmm, seems like this one breaks compatibility with TeXLive 2020. Just checked this on Overleaf. I am inclined to roll this back or remove it altogether since it is not required for the template to be built. I still want to have `siunitx` as a dependency, but the `\sisetup` could be done in `Thesis.tex` itself as an example only.

**Comment by holgerdell** [comment]
Your proposal sounds good!

**Comment by Pseudomanifold** [comment]
Thanks, it's updated now :)

**Comment by holgerdell** [comment]
Hm, the current version of mimosis.cls still contains \sisetup, doesn't it?

**Comment by Pseudomanifold** [comment]
You are right, sorry! Forgot to update this; fixed in 816113f84d2aa207944a546c3a0b6541cd7b06d7.

**Pull request merged**
