### PR TITLE
Continuous Integration using GitHub Actions

### PR DESCRIPTION
**Pull request by holgerdell**
Generated binary files such as Thesis.pdf should generally not be added to git.

This pull request will remove Thesis.pdf, and have GitHub Actions compile it for you after every push. The file will then be available at https://pseudomanifold.github.io/latex-mimosis/Thesis.pdf. All you have to do (once) after accepting the pull request is go to the repository's Settings -> Pages. Select "Deploy from a branch" and set the Branch to gh-pages.

### CODE REVIEW

**Comment by Pseudomanifold** [comment]
Thanks—this is something I wanted to do for a long time! Unfortunately, the LaTeX compilation fails at the moment; I'll see whether changing the default engine might help. Weirdly enough, the current error is:

```
l.25 \AtEveryBibitem
                  {\clearfield{month}}
? 
./bibliography-mimosis.tex:25: Emergency stop.
```

**Comment by holgerdell** [comment]
The issue is caused by "*.tex" in the workflow yaml file, because it then tries to compile all tex files. Simply replace with Thesis.tex. Sorry, I didn't notice this in my test, as I had deleted the other file.

**Comment by Pseudomanifold** [comment]
Thanks, just also stumbled over this :-) It would be amazing if there was a `latexmk` action that respected the `latexmkrc` directly, but your solution is very nice!

**Comment by Pseudomanifold** [comment]
Works like a charm now! Thanks so much :pray: !

**Pull request merged**
